### ISSUE TITLE
Settings icon disappears when theme is activated

### ISSUE THREAD

**Issue by DimTheEnderman** [davart154/DTM-18#10]
OldCord
![Screenshot 2024-06-07 234722](https://github.com/davart154/DTM-18/assets/169503763/ba9f4002-7179-4e52-8485-7157400b8db3)
DTM-18
![Screenshot 2024-06-07 234100](https://github.com/davart154/DTM-18/assets/169503763/452132ce-2714-43b1-80cd-306276675ca1)

**Comment by davart154** [comment]
I think I remove the width limit of the username so it's pushing the button off to the side (maybe). I'll fix it when I can.
