### ISSUE TITLE
Very Laggy

### ISSUE THREAD

**Issue by Clyde6790pGIT** [davart154/DTM-18#15]
Applying this theme causes Discord to turn into a slideshow, although the theme looks great, it causes my whole system to lag out until I remove it.

**Comment by Beanudt** [comment]
Same

**Comment by nik0la123456** [comment]
yeah ive got the same problem

**Comment by davart154** [comment]
I've been trying different ways to solve this issue for like a year now and it still happens. I can't promise anything but I'll continue to look through things to see what makes it lag.
