### ISSUE TITLE
The newset version settings are bugged

### ISSUE THREAD

**Issue by PurpleBored** [davart154/DTM-18#4]
So yeah in the newest version, the place of the settings are all over the place like Vencord settings are on the top account settings are hidden at the bottom, etc

**Comment by davart154** [comment]
Thanks for letting me know! The settings were originally only designed with bd and unmodded clients in mind, but i'll make sure to push out a change soon fixing this for Vencord.

**Comment by davart154** [comment]
Should be fixed. Let me know if there are any other issues.
