### ISSUE TITLE
Call theme and icons are back to regular

### ISSUE THREAD

**Issue by imapancake22** [davart154/DTM-18#7]
Title. The call theme has switched back to the regular call theme and the icons have switched back to the regular icons. I don't know CSS but please fix the theme I really like it

**Comment by davart154** [comment]
Thanks for letting me know. They changed to lottie so I can't use the usual method so it'll take a bit of time to fix, but I'll get on it when I can.

**Comment by wont-stream** [comment]
I'd like to say they are now just blank squares
![{8C17FF40-F1C6-4AC4-ABAA-0DD206653579}](https://github.com/user-attachments/assets/e2f00d8f-034f-40d4-9d18-0cf0d188e972)

**Comment by imapancake22** [comment]
How did you get my email and why are you telling this to me out of all
people

**Comment by wont-stream** [comment]
@imapancake22 GitHub sends you emails, people do not send you emails. Your email is not public.

**Comment by imapancake22** [comment]
my bad
